AWSTemplateFormatVersion: "2010-09-09"
Description: chibiharu's Qiita [【AWS】CloudFormationでWebサーバを構築①（NW編）] - SecurityTemplate


# ------------------------------------------------------------
# Input Parameters
# ------------------------------------------------------------
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
    

### Resources ###
Resources:
# ------------------------------------------------------------
# SecurityGroup
# ------------------------------------------------------------
### ALB Server Security Group ###
    chibiALBSG:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "http,https public"
            GroupName: cfn-dev-alb-sg
            VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
            Tags: 
                - Key: Name
                  Value: !Sub "${PJPrefix}-alb-sg"
            SecurityGroupIngress:
                IpProtocol: tcp
                FromPort : 80
                ToPort : 80
                CidrIp: 0.0.0.0/0
                IpProtocol: tcp
                FromPort : 443
                ToPort : 443
                CidrIp: 0.0.0.0/0
                
### Web Server Security Group ###
    chibiWebSG:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "http public"
            GroupName: cfn-dev-web-sg
            VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
            Tags: 
                - Key: Name
                  Value: !Sub "${PJPrefix}-web-sg"
            SecurityGroupIngress:
                IpProtocol: tcp
                FromPort : 80
                ToPort : 80
                SourceSecurityGroupId: !Ref chibiALBSG

### Database Server Security Group ###            
    chibidbSG:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "db private"
            GroupName: cfn-dev-db-sg
            VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
            Tags: 
                - Key: Name
                  Value: !Sub "${PJPrefix}-db-sg"
            SecurityGroupIngress:
                IpProtocol: tcp
                FromPort : 3306
                ToPort : 3306
                SourceSecurityGroupId: !Ref chibiWebSG
        

# ------------------------------------------------------------
# Output Parameter
# ------------------------------------------------------------
Outputs:
### SecurityGroup ###
    chibiALBSG:
        Value: !Ref chibiALBSG
        Export:
            Name: !Sub "${PJPrefix}-alb-sg"
    chibiWebSG:
        Value: !Ref chibiWebSG
        Export:
            Name: !Sub "${PJPrefix}-web-sg"
    chibidbSG:
        Value: !Ref chibidbSG
        Export:
            Name: !Sub "${PJPrefix}-db-sg"
